//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QSM_Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class matricula
    {
        public int usuario_id { get; set; }
        public int modulo_id { get; set; }
        public int habilitado { get; set; }
        public Nullable<int> intentos { get; set; }
    
        public virtual modulo modulo { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
