//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QSM_Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class modulo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public modulo()
        {
            this.matricula = new HashSet<matricula>();
            this.session_certificado = new HashSet<session_certificado>();
            this.subcategoria = new HashSet<subcategoria>();
        }
    
        public int modulo_id { get; set; }
        public int empresa_id { get; set; }
        public string nombre_modulo { get; set; }
        public string descripcion_modulo { get; set; }
        public int tiempo_certificacion { get; set; }
        public int cantidad_preguntas { get; set; }
        public int habilitado { get; set; }
        public double porcentaje_certificacion { get; set; }
        public Nullable<int> score_model_id { get; set; }
    
        public virtual empresa empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<matricula> matricula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<session_certificado> session_certificado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<subcategoria> subcategoria { get; set; }
    }
}
