//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QSM_Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class respuesta_pregunta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public respuesta_pregunta()
        {
            this.session_certificado = new HashSet<session_certificado>();
        }
    
        public int respuesta_pregunta_id { get; set; }
        public int pregunta_id { get; set; }
        public string enunciado_respuesta { get; set; }
        public int respuesta_correcta { get; set; }
    
        public virtual pregunta pregunta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<session_certificado> session_certificado { get; set; }
    }
}
