//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QSM_Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class session_certificado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public session_certificado()
        {
            this.respuesta_pregunta = new HashSet<respuesta_pregunta>();
        }
    
        public int session_certificado_id { get; set; }
        public int modulo_id { get; set; }
        public System.DateTime inicio_session { get; set; }
        public System.DateTime final_session { get; set; }
        public int certificado { get; set; }
        public int ayuda50 { get; set; }
        public int ayuda_publico { get; set; }
        public int ayuda_cambio { get; set; }
        public Nullable<int> usuario_id { get; set; }
    
        public virtual modulo modulo { get; set; }
        public virtual usuario usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<respuesta_pregunta> respuesta_pregunta { get; set; }
    }
}
