//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QSM_Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class subcategoria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public subcategoria()
        {
            this.pregunta = new HashSet<pregunta>();
        }
    
        public int subcategoria_id { get; set; }
        public int modulo_id { get; set; }
        public string nombre_subcategoria { get; set; }
        public string descripcion_subcategoria { get; set; }
        public Nullable<int> habilitada { get; set; }
    
        public virtual modulo modulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pregunta> pregunta { get; set; }
    }
}
