//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QSM_Manager.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuario()
        {
            this.matricula = new HashSet<matricula>();
            this.session_certificado = new HashSet<session_certificado>();
        }

        public int usuario_id { get; set; }
        [Display(Name = "Empresa")]
        public int empresa_id { get; set; }
        [Display(Name = "Tipo de usuario")]
        public int tipo_usuario_id { get; set; }
        [Display(Name = "Nombre(s)")]
        public string nombres { get; set; }
        [Display(Name = "Apellido(s)")]
        public string apellidos { get; set; }
        [Display(Name = "Documento/Usuario")]
        public string documento_identificacion { get; set; }
        [Display(Name = "Password")]
        public string password { get; set; }
        [Display(Name = "Sexo")]
        public int sexo { get; set; }
        [Display(Name = "Fecha de registro")]
        public Nullable<System.DateTime> fecha_registro { get; set; }
        [Display(Name = "último ingreso")]
        public Nullable<System.DateTime> ultimo_ingreso { get; set; }
        [Display(Name = "Correo electrónico")]
        public string correo { get; set; }
        [Display(Name = "Grupo")]
        public int grupo_id { get; set; }
        [Display(Name = "Fecha de nacimiento")]
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
    
        public virtual empresa empresa { get; set; }
        public virtual Grupo Grupo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<matricula> matricula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<session_certificado> session_certificado { get; set; }
        public virtual tipo_usuario tipo_usuario { get; set; }
    }
}
